spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: spring boot datasource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    banner-mode: off

# MyBatis 配置（可选，根据持久层框架调整）
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zengyanyu.*.entity