server:
  port: 8082
  servlet:
    context-path: /

spring:
  datasource:
    # 数据源1（主数据源：业务库）
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源2（从数据源：日志库）
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/clouddb02?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.apache.ibatis: debug